spring:
  application:
    name: seckill-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /
  thymeleaf:
    cache: false
server:
  port: 25000