server:
  port: 5555
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/gmall_oms?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    virtual-host: /
    # 开启发送端被broker收到的确认（P->E）
    publisher-confirms: true
    # 开启发送端消息抵达队列的确认（E->Q）
    publisher-returns: true
    # 只要抵达队列，就会以异步模式优先回调returnconfirm
    template:
      mandatory: true
    # 消费者手动ack（确认）消息
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.56.10
    port: 6379
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

  # 服务追踪发现
  zipkin:
    base-url: http://192.168.56.10:9411/
    # 关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false
# 开启debug日志
log:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
mall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10


