server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coin-exchange?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.56.10
#    port: 6379