#spring:
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器地址
#    host: localhost
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    # password: admin
#    # 连接超时时间（毫秒）
#    timeout: 3000ms
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 20
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 3000ms
#        # 连接池中的最大空闲连接（负数没有限制）
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0
spring:
  # Redis
  redis:
    cluster:
      nodes: 192.168.188.152:7000,192.168.188.152:7001,192.168.188.152:7002,192.168.188.152:7003,192.168.188.152:7004,192.168.188.152:7005
    database: 0
    password: shield@2019
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-wait: 5000
        max-idle: 10
        min-idle: 0
      shutdown-timeout: 50ms