server:
  port: 8082
spring:
  application:
    name: rabbit-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 消费者手动ack（确认）消息
    listener:
      direct:
        acknowledge-mode: manual
