server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 不区分大小写，都可以路由到
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1 # 将当前访问/admin/login -> 将admin自动去掉
        - id: member-service_router
          uri: lb://coin-member-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1 # 将当前访问/user/login -> 将user自动去掉

    sentinel:
      datasource:
        ds1.nacos:
          server-addr: nacos-server:8848
          data-id: gw-flow
          rule-type: gw-flow
        ds2.nacos:
          server-addr: nacos-server:8848
          data-id:  api-group
          rule-type: gw-api-group
      transport:
        dashboard: localhost:8333
        port: 8333
      eager: true # 服务启动直接建立心跳连接
  redis:
    host: 192.168.56.10
    port: 6379
#        ds1.file:
#          file: classpath:gw-flow.json # 网关 + API分组的限流
#          ruleType: gw_flow
#        ds2.file:
#          file: classpath:api-group.json # api-flow.json 接口的分组
#          ruleType: gw_api_group
management:
  endpoints:
    web:
      exposure:
        include: '*'