# 开发环境配置
server:
  servlet:
    session:
      timeout: 720m  # session超时时间为12小时，单位分钟
  tomcat:
    uri-encoding: utf-8  # tomcat的URI编码
    max-threads: 800     # 最大线程数
  port: 9100
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 项目中后台返回给前台的时间格式化格式，如果想换成yyyy-MM-dd,可在时间类型的属性或者get()方法上添加注解jackson的@JsonFormat(pattern = "yyyy-MM-dd",timezone = "GTM+8")
    time-zone: Asia/Chongqing        # 时区设置
    # 启动热部署
    devtools:
      restart:
        enabled: false
  datasource: # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 在spring boot 配置文件中datasource url 增加serverTimezone=UTC 参数，其中UTC是统一标准世界时间
    url: jdbc:mysql://127.0.0.1:3306/mybatisplus?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: admin
    druid:
      initial-size: 20 # 初始化连接大小
      min-idle: 20     # 最小空闲连接数
      max-active: 100  # 最大连接数
      max-wait: 60000  # 最大等待时间
      filters: stat,config
      transaction-query-timeout: 60000 #事务查询超时时间
      remove-abandoned-timeout: 1600
      test-while-idle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      min-evictable-idle-time-millis: 360000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      query-timeout: 60000 # 查询超时时间
      validation-query: select * from dual # 连接检查
      stat-view-servlet:
        enabled: true # 开启druid监控
        login-username: admin
        login-password: admin
        allow:  # 白名单
        deny:   # 黑名单
        url-pattern: "/druid/*"
    hikari:
      read-only:
  #    type: com.alibaba.druid.pool.DruidDataSource # 类型

  # redis配置
  cache:
    type: redis
    redis:
      time-to-live: 20000 #缓存超时时间ms
      cache-null-values: false #是否缓存空值
  redis:
    port: 6379
    host: 127.0.0.1  # 127.0.0.1
    password: 123456 # Redis 服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
    timeout: 10000  #redis 连接超时时间ms
    database: 0 # 数据库索引，默认是0


mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  ##主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  #mybatis-plus.global-config.id-type=3
  ##字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  #mybatis-plus.global-config.field-strategy=2
  #驼峰下划线转换
  global-config:
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #mybatis-plus.global.table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    #mybatis-plus.global-config.key-generator=com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  #mybatis-plus.global-config.sql-injector=com.baomidou.springboot.MyMetaObjectHandler
  #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #控制台是否显示sql
  #mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

