server:
  port: 40000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cart-service
  redis:
    host: 192.168.56.10
  session:
    store-type: redis