server:
  port: 40000
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: cart-service
  redis:
    host: 192.168.56.10
  session:
    store-type: redis

  # 服务追踪发现
  zipkin:
    base-url: http://192.168.56.10:9411/
    # 关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false
# 开启debug日志
log:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

mall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10