spring:
  cloud:
    gateway:
      routes:
        - id: test_route #唯一id
          uri: https://www.baidu.com #跳转的路径
          predicates: # 断言
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://third-party-service
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://ware-service
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        ##lb：代表负载均衡
        - id: admin_route
          uri: lb://admin-vue
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/admin-vue/$\{segment}

        - id: gmall_search_route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: gmall_cart_route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: gmall_auth_route
          uri: lb://auth-service
          predicates:
            - Host=auth.gmall.com
        # host域名映射配置跳转需要放置最下面，否则上述无法路由到其他服务接口
        # 所有的页面请求和接口请求都通过nginx反向代理到网关，网关配置域名映射跳转到响应的接口或者页面
        # 如果是/api/**,转交给对应的服务器请求接口，如果满足域名，则转交给对应的服务，比如下面的product-service服务
        - id: gmall_host_route
          uri: lb://product-service
          predicates:
            - Host=gmall.com,item.gmall.com



## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree

